version: 2

defaults: &defaults
  working_directory: ~/repo
  environment:
    TZ: "/usr/share/zoneinfo/Europe/Amsterdam"
  docker:
    - image: circleci/node:8-browsers
      environment:
        TZ: "/usr/share/zoneinfo/Europe/Amsterdam"

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-deps-{{ .Branch }}-
            - v1-deps-
      - run: yarn
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/repo
          paths: .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn test
      - store_artifacts:
          path: coverage

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run: yarn deploy

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - lint
            - test
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         only:
      #           - master
